document.getElementById("myheader").innerHTML = 

    "<nav>"
        +"&nbsp <a href='index.html'>Página inicial</a>"
        +"  <a href=''>Segundo elemento</a>"
        +"  <a href=''>3 elemento</a>"
        +"  <a href=''>4 elemento</a>"
        +" <!--Itens à direita da barra de nav-->"
        +"<div>"
        +"<label>Qual a sua cidade?</label>"
        +"<select id='selctCidade'>"
            +"<option value='1'>Olinda - PE</option>"
            +"<option value='3'>Paulista - PE</option>"
            +"<option value='4'>Camaragibe - PE</option>"
            +"<option value='5'>Fortaleza - CE</option>"
        +"</select>"
        +"<select id='selctCinema'>"
            +"<option value='1'>Shopping Patteo Olinda</option>"
            +"<option value='3'>Paulista Northway</option>"
            +"<option value='4'>Camará Shopping</option>"
            +"<option value='5'>RioMar Kennedy</option>"
        +"</select>"
    +"</div>"
        +"<div>"
        +"  <a href=''>Login </a>"
        +"&nbsp &nbsp <a href=''>Cadastrar</a>"
        +"</div>"
    +"</nav>";